/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.ecorous.boardbot

import dev.kordex.core.ExtensibleBot
import dev.kord.gateway.Intent
import dev.kord.gateway.PrivilegedIntent
import org.ecorous.boardbot.extensions.BoardExtension
import org.slf4j.Logger
import org.slf4j.LoggerFactory

val logger: Logger = LoggerFactory.getLogger("BoardBot")

@OptIn(PrivilegedIntent::class)
suspend fun main() {


	val success = DatabaseHandler.init()
	if (!success) {
		logger.error("Failed to initialize the database. Bailing out!")
		return
	}
	val bot = ExtensibleBot(Environment.TOKEN) {
		intents {
			+Intent.MessageContent
		}
		extensions {
			add(::BoardExtension)
		}
	}

	bot.start()
}
